const es = {
  meta: {
    tituloLanding: "Entreobra — Entre tu obra y tu proveedor",
    tituloDemo: "Demo — Entreobra",
  },
  preferencias: {
    idioma: "Idioma",
    temaClaro: "Usar tema claro",
    temaOscuro: "Usar tema oscuro",
  },
  header: {
    irInicio: "Entreobra, ir al inicio",
    nav: { comparar: "Comparar", "como-funciona": "Cómo funciona", proveedores: "Proveedores", demo: "Demo", acceso: "Contacto" },
    abrirMenu: "Abrir menú",
    cerrarMenu: "Cerrar menú",
    ctaMovil: "Quiero acceso anticipado",
    ubicacion: "Cochabamba · Bolivia",
  },
  hero: {
    ubicacion: "Cochabamba · Bolivia",
    proximamente: "Próximamente",
    titulo: ["Entre tu obra", "y tu proveedor."],
    bajada: "Mira quién tiene stock ahora y a qué precio, sin perder la mañana en WhatsApp.",
    cta: "Quiero acceso anticipado",
    ctaProveedor: "Soy proveedor",
    gratis: "Gratis",
    metricas: ["Pasos, sin llamadas", "Entre el más caro y el más barato (ejemplo)", "Categorías comparadas", "Costo del acceso anticipado"],
  },
  materiales: {
    etiqueta: "Materiales",
    titulo: ["Todo lo que necesitas,", "comparado en un lugar."],
    verTodo: "Ver todo",
    categorias: [
      { nombre: "Cemento", detalle: "IP-30, IP-40, blanco" },
      { nombre: "Fierro y acero", detalle: "Corrugado, alambre, mallas" },
      { nombre: "Áridos", detalle: "Arena, grava, ripio" },
      { nombre: "Ladrillos y bloques", detalle: "Gambote, 6 huecos, bloques" },
      { nombre: "Cerámicos", detalle: "Pisos, revestimientos, porcelanato" },
      { nombre: "Tuberías y sanitarios", detalle: "PVC, desagüe, grifería" },
    ],
    centroTitulo: ["Mira quién tiene stock", "ahora y a qué precio."],
    centroCta: "Quiero acceso anticipado",
  },
  problema: {
    etiqueta: "El problema",
    titulo: ["Hoy, pedir material", "se ve así."],
    bajada: "Cuatro chats abiertos y ninguna respuesta clara.",
    chat: "WhatsApp · 4 chats",
    esperando: "Esperando",
    intercambios: [
      { pregunta: "¿A cuánto la bolsa de cemento?", respuesta: "Déjeme consultar" },
      { pregunta: "¿Y el flete hasta la obra?", respuesta: "Eso es aparte" },
      { pregunta: "¿Ya salió el camión?", respuesta: "Visto" },
    ],
    dolores: [
      { titulo: "Cotizas uno por uno", detalle: "La misma pregunta, en cuatro chats distintos." },
      { titulo: "Comparas de memoria", detalle: "Los precios llegan sueltos, cuando llegan." },
      { titulo: "Coordinas cada flete aparte", detalle: "El transporte es otra conversación." },
      { titulo: "Nadie sabe cuándo llega", detalle: "El camión sale cuando sale." },
    ],
    cierre: ["Y mientras tanto, ", "la obra espera", "."],
  },
  comoFunciona: {
    etiqueta: "Cómo funciona",
    titulo: "Cuatro pasos, sin llamadas.",
    pasos: [
      { titulo: "Registra tu obra", descripcion: "Tus pedidos y gastos quedan ordenados por proyecto." },
      { titulo: "Busca el material", descripcion: "Ves quién lo tiene en stock y a qué precio." },
      { titulo: "Arma tu pedido", descripcion: "Un solo pedido, aunque venga de varios proveedores." },
      { titulo: "Recibe en obra", descripcion: "Coordinas la entrega directo en tu obra." },
    ],
    mocks: {
      nuevaObra: "Nueva obra",
      nombreObra: "Edificio Torre del Bosque",
      zona: "Cochabamba · Cercado",
      crearObra: "Crear obra",
      producto: "Cemento IP-30",
      tuPedido: "Tu pedido",
      lineas: ["Cemento IP-30 x5", "Fierro 3/8 x10"],
      total: "Total",
      pedido: "Pedido #4821",
      estados: ["Confirmado", "En preparación", "En camino", "Entregado"],
    },
  },
  comparador: {
    etiqueta: "Comparador",
    titulo: ["No es un catálogo.", "Es un comparador."],
    bajada:
      "Otras páginas te muestran productos. Entreobra te muestra cuál te conviene, según precio, stock, distancia y quién cumple.",
    ventajas: [
      "Mismo material, varios proveedores",
      "Un pedido, aunque venga de tres ferreterías",
      "Cada gasto ordenado por obra",
    ],
    producto: "Cemento IP-30 · 50 bolsas",
    total: "Total",
    estadoFinal: "Ordenado por precio total",
    comparando: (n: string) => `Comparando ${n} ferreterías…`,
    mejorPrecio: "Mejor precio",
    stock: ["180 bolsas en stock", "90 bolsas en stock", "stock sin confirmar"],
    ahorras: ["Ahorras ", " eligiendo el mejor precio de ", " proveedores"],
    nota: "Ejemplo ilustrativo: ferreterías y precios ficticios.",
    numeros: ["uno", "dos", "tres", "cuatro", "cinco"],
  },
  dosLados: {
    etiqueta: "Dos lados",
    titulo: "Una sola plataforma.",
    bajada: "Entreobra está entre tu obra y tu proveedor. ¿De qué lado estás?",
    lados: [
      {
        etiqueta: "Si estás en obra",
        palabra: "Obra",
        titulo: ["Residentes, ingenieros", "y contratistas"],
        puntos: [
          "Comparas proveedores sin salir de la obra",
          "Pides todo junto, aunque venga de varios lados",
          "Tus gastos quedan ordenados por proyecto",
        ],
        cta: "Sin costo · Empezar",
      },
      {
        etiqueta: "Si vendes materiales",
        palabra: "Proveedor",
        titulo: ["Ferreterías, distribuidores", "e importadores"],
        puntos: [
          "Te encuentran obras que hoy no te conocen",
          "Recibes pedidos claros, sin cotizar por chat",
          "Sin comisión por venta: una cuota fija, informada antes de cobrar",
        ],
        cta: "Entrar como fundador",
      },
    ],
  },
  formulario: {
    etiqueta: "Acceso anticipado",
    titulo: ["Sé de los primeros", "en usarlo."],
    bajada: "Estamos armando la plataforma en Cochabamba. Déjanos tus datos y te avisamos apenas abramos.",
    nombre: "Nombre",
    nombrePlaceholder: "Tu nombre",
    participas: "¿Cómo participas?",
    opciones: { obra: "Estoy en obra", proveedor: "Vendo materiales" },
    whatsapp: "WhatsApp",
    enviar: "Avísenme cuando abra",
    enviando: "Enviando…",
    nota: "Sin costo y sin compromiso. Solo te escribimos cuando la plataforma esté lista.",
    consentimiento: ["Acepto la ", "Política de privacidad", " y que Entreobra me escriba por WhatsApp sobre el acceso anticipado."],
    exitoTitulo: "Listo, ya estás anotado.",
    waTitulo: "Solo falta enviar el mensaje.",
    waTexto: "Te abrimos WhatsApp con tus datos ya escritos. Envíalo y quedas anotado.",
    abrirWa: "Abrir WhatsApp",
    enviarPorWa: "Enviar por WhatsApp",
    errorGenerico: "No se pudo enviar. Intenta de nuevo.",
    errorConexion: "No pudimos conectarnos. Intenta de nuevo o mándanos tu registro por WhatsApp.",
    mensajeWa: (nombre: string, participa: string, whatsapp: string) =>
      [
        "Hola, quiero acceso anticipado a Entreobra.",
        `Nombre: ${nombre}`,
        `Participo como: ${participa}`,
        `Mi WhatsApp: ${whatsapp}`,
        "Acepto la Política de privacidad de Entreobra.",
      ].join("\n"),
  },
  footer: {
    ubicacion: "Cochabamba, Bolivia",
    contacto: "Contacto",
    siguenos: "Síguenos",
  },
  instalar: {
    boton: "Instalar app",
    titulo: "Entreobra en tu celular",
    sub: "Como cualquier app, a un toque",
    iosCompartir: ["Toca el ícono de ", "compartir", " en la barra de Safari."],
    iosAgregar: ["Desliza y elige ", "Agregar a pantalla de inicio", "."],
    iosListo: ["Toca ", "Agregar", " arriba a la derecha. Listo."],
    texto: "Te queda un ícono como cualquier app, abre a pantalla completa y funciona más rápido — sin pasar por una tienda de apps.",
    instalar: "Instalar Entreobra",
    cerrar: "Cerrar",
  },
  volverArriba: "Volver arriba",
  saltarContenido: "Saltar al contenido",
  demo: {
    etiqueta: "Vista previa · App completa",
    titulo: "Así se ve Entreobra por dentro.",
    bajada:
      "Un adelanto de la aplicación, más allá de la landing. Seis momentos: del que compra, del que vende y del que transporta.",
    avisoEtiqueta: "Vista previa · En desarrollo",
    avisoTitulo: "Esto no es el producto final.",
    avisoTexto:
      "Las pantallas muestran hacia dónde va Entreobra. La app está en desarrollo: el diseño, los datos, las empresas y los precios son de ejemplo, y pueden cambiar antes del lanzamiento.",
    ctaTitulo: "¿Te interesa llevar esto adelante?",
    ctaTexto: "Cuéntanos qué te pareció.",
    ctaBoton: "Hablemos de esto",
    volver: "Volver a la landing",
    appPorDentro: "La app por dentro",
    notaTelefono: "* Pantallas de prueba. El diseño y los datos están sujetos a cambios.",
    pasos: [
      {
        titulo: "Tu inicio",
        descripcion: "Al abrir la app ves lo importante: tus pedidos en curso, las empresas que te venden y tus obras.",
        focos: [
          { titulo: "Lo que ahorras, a la vista", texto: "Cada compra comparando suma la diferencia. Sabes cuánto te rinde usar Entreobra." },
          { titulo: "Tu pedido en curso, primero", texto: "Lo que está en camino aparece arriba, con la hora estimada de llegada." },
          { titulo: "Las empresas que te venden", texto: "Ferreterías y distribuidoras de Cochabamba con su calificación, distancia y si tienen stock." },
          { titulo: "Todo por obra", texto: "Cada obra con sus pedidos y gastos por separado. Nada se mezcla." },
        ],
      },
      {
        titulo: "Busca y compara",
        descripcion: "Un solo catálogo para todos los materiales, con precios de varias ferreterías lado a lado.",
        focos: [
          { titulo: "Busca como lo pides en obra", texto: "Escribe «cemento», «fierro 3/8» o la marca. Sin códigos ni catálogos en PDF." },
          { titulo: "Filtra en un toque", texto: "Cemento, fierro, áridos, ladrillos: tocas una categoría y ves solo eso." },
          { titulo: "El mejor precio, primero", texto: "Cada producto te dice cuántas ferreterías lo tienen y desde cuánto. Lo tocas y comparas lado a lado." },
        ],
      },
      {
        titulo: "Arma tu pedido",
        descripcion: "Todo en un carrito, aunque los productos vengan de proveedores distintos.",
        focos: [
          { titulo: "Ordenado por ferretería", texto: "Si el pedido sale de dos proveedores, ves qué trae cada uno. Igual es un solo pedido." },
          { titulo: "Cantidades al toque", texto: "Subes o bajas bolsas, varillas o ladrillos sin volver a buscar el producto." },
          { titulo: "Llega a tu obra", texto: "Eliges la obra y el día. La dirección ya está guardada." },
          { titulo: "Un total, un botón", texto: "Confirmas una vez y cada ferretería recibe su parte del pedido." },
        ],
      },
      {
        titulo: "Síguelo en vivo",
        descripcion: "Del taller a la obra: sabes en qué paso está tu pedido en cada momento, sin preguntar.",
        focos: [
          { titulo: "Míralo llegar", texto: "El camión en el mapa, del depósito a tu obra, en tiempo real." },
          { titulo: "Sabes cuándo llega", texto: "Tiempo estimado, quién lo trae y en qué vehículo. Sin llamar a preguntar." },
          { titulo: "Cada paso, con hora", texto: "Confirmado, en preparación, en camino, entregado. Queda registro de todo." },
        ],
      },
      {
        titulo: "Si tienes una ferretería",
        descripcion: "Publica tu catálogo y gestiona tus pedidos entrantes desde un panel propio.",
        focos: [
          { titulo: "Tu negocio de un vistazo", texto: "Pedidos, pendientes y lo vendido, siempre al día." },
          { titulo: "Cómo va la semana", texto: "Ves qué días vendes más para tener stock cuando hace falta." },
          { titulo: "Pedidos que llegan solos", texto: "Obras cercanas te piden directo, listos para preparar. Sin perseguir clientes por WhatsApp." },
        ],
      },
      {
        titulo: "Si haces fletes",
        descripcion: "Recibe fletes disponibles cerca tuyo y acéptalos con un toque.",
        focos: [
          { titulo: "Trabajas cuando quieres", texto: "Te pones disponible y empiezan a llegar fletes cerca tuyo." },
          { titulo: "De dónde a dónde", texto: "Origen, destino, distancia y qué vas a cargar, antes de aceptar." },
          { titulo: "Aceptas con un toque", texto: "El flete es tuyo y la ferretería ya sabe quién va a buscar el pedido." },
        ],
      },
    ],
  },
  app: {
    pestanasComprador: ["Inicio", "Buscar", "Pedido", "Obras"],
    pestanasFerreteria: ["Panel", "Pedidos", "Catálogo", "Cuenta"],
    pestanasChofer: ["Fletes", "Ruta", "Ganancias", "Perfil"],
    inicio: {
      etiqueta: "Buenos días",
      titulo: "Tus obras",
      ahorro: "Ahorraste este mes",
      pedido: "Pedido #4821",
      enCamino: "En camino",
      llega: "Llega en 25 min a Torre del Bosque",
      empresas: "Empresas que te venden",
      verTodas: "Ver todas",
      conStock: "Con stock",
      sinConfirmar: "Sin confirmar",
      obras: [
        { nombre: "Torre del Bosque", detalle: "3 pedidos · Bs 1.150" },
        { nombre: "Casa Sacaba #12", detalle: "1 pedido · Bs 480" },
      ],
    },
    catalogo: {
      etiqueta: "Torre del Bosque",
      titulo: "Catálogo",
      buscar: "Buscar material…",
      filtros: ["Todo", "Cemento", "Fierro", "Áridos"],
      productos: ["Cemento IP-30", "Fierro 3/8", "Ladrillo 6H", "Pintura 20L", "Arena fina", 'Tubo PVC 4"'],
      proveedores: (n: number) => `${n} proveedores`,
      desde: "desde",
    },
    carrito: {
      etiqueta: "3 productos · 2 proveedores",
      titulo: "Tu pedido",
      productos: ["Cemento IP-30", "Fierro 3/8", "Ladrillo 6H"],
      entrega: "Entrega en obra",
      entregaDetalle: "Torre del Bosque · mañana",
      total: "Total",
      confirmar: "Confirmar pedido",
    },
    seguimiento: {
      etiqueta: "En camino",
      titulo: "Pedido #4821",
      llegaEn: "Llega en",
      vehiculo: "Ferretería A · Toyota Dyna",
      estados: ["Confirmado", "En preparación", "En camino", "Entregado"],
    },
    panel: {
      titulo: "Mi ferretería",
      stats: ["Pedidos", "Pendientes", "Vendido"],
      semana: "Esta semana",
      entrantes: "Pedidos entrantes",
      pedidos: [
        { obra: "Edificio Torre del Bosque", detalle: "Cemento IP-30 ×5" },
        { obra: "Casa Sacaba #12", detalle: "Fierro 3/8 ×10" },
        { obra: "Galpón Quillacollo", detalle: "Ladrillo 6H ×200" },
      ],
      nuevo: "Nuevo",
      preparando: "Preparando",
    },
    fletes: {
      etiqueta: "Cerca de ti",
      titulo: "Fletes",
      disponible: "Disponible",
      cargas: ["Cemento ×5 · Fierro ×10", "Ladrillo 6H ×200"],
      aceptar: "Aceptar",
    },
  },
};

export type Textos = typeof es;

const en: Textos = {
  meta: {
    tituloLanding: "Entreobra — Between your job site and your supplier",
    tituloDemo: "Demo — Entreobra",
  },
  preferencias: {
    idioma: "Language",
    temaClaro: "Use light theme",
    temaOscuro: "Use dark theme",
  },
  header: {
    irInicio: "Entreobra, go to top",
    nav: { comparar: "Compare", "como-funciona": "How it works", proveedores: "Suppliers", demo: "Demo", acceso: "Contact" },
    abrirMenu: "Open menu",
    cerrarMenu: "Close menu",
    ctaMovil: "I want early access",
    ubicacion: "Cochabamba · Bolivia",
  },
  hero: {
    ubicacion: "Cochabamba · Bolivia",
    proximamente: "Coming soon",
    titulo: ["Between your job site", "and your supplier."],
    bajada: "See who has stock right now and at what price, without losing the morning on WhatsApp.",
    cta: "I want early access",
    ctaProveedor: "I'm a supplier",
    gratis: "Free",
    metricas: ["Steps, no calls", "Between the most and least expensive (example)", "Categories compared", "Early access cost"],
  },
  materiales: {
    etiqueta: "Materials",
    titulo: ["Everything you need,", "compared in one place."],
    verTodo: "See all",
    categorias: [
      { nombre: "Cement", detalle: "IP-30, IP-40, white" },
      { nombre: "Rebar and steel", detalle: "Corrugated, wire, mesh" },
      { nombre: "Aggregates", detalle: "Sand, gravel, crushed stone" },
      { nombre: "Bricks and blocks", detalle: "Solid, hollow, blocks" },
      { nombre: "Ceramics", detalle: "Floors, wall tiles, porcelain" },
      { nombre: "Pipes and sanitary", detalle: "PVC, drainage, fixtures" },
    ],
    centroTitulo: ["See who has stock", "now and at what price."],
    centroCta: "I want early access",
  },
  problema: {
    etiqueta: "The problem",
    titulo: ["Ordering materials today", "looks like this."],
    bajada: "Four open chats and no clear answer.",
    chat: "WhatsApp · 4 chats",
    esperando: "Waiting",
    intercambios: [
      { pregunta: "How much for a bag of cement?", respuesta: "Let me check" },
      { pregunta: "And delivery to the site?", respuesta: "That's extra" },
      { pregunta: "Has the truck left yet?", respuesta: "Seen" },
    ],
    dolores: [
      { titulo: "You quote one by one", detalle: "The same question, in four different chats." },
      { titulo: "You compare from memory", detalle: "Prices arrive scattered, if they arrive." },
      { titulo: "You arrange each delivery separately", detalle: "Transport is another conversation." },
      { titulo: "Nobody knows when it arrives", detalle: "The truck leaves whenever it leaves." },
    ],
    cierre: ["And meanwhile, ", "the site waits", "."],
  },
  comoFunciona: {
    etiqueta: "How it works",
    titulo: "Four steps, no calls.",
    pasos: [
      { titulo: "Register your site", descripcion: "Your orders and costs stay organized by project." },
      { titulo: "Find the material", descripcion: "See who has it in stock and at what price." },
      { titulo: "Build your order", descripcion: "One single order, even if it comes from several suppliers." },
      { titulo: "Receive it on site", descripcion: "Coordinate delivery straight to your site." },
    ],
    mocks: {
      nuevaObra: "New site",
      nombreObra: "Torre del Bosque building",
      zona: "Cochabamba · Cercado",
      crearObra: "Create site",
      producto: "Cement IP-30",
      tuPedido: "Your order",
      lineas: ["Cement IP-30 x5", "Rebar 3/8 x10"],
      total: "Total",
      pedido: "Order #4821",
      estados: ["Confirmed", "Being prepared", "On the way", "Delivered"],
    },
  },
  comparador: {
    etiqueta: "Comparison",
    titulo: ["It's not a catalog.", "It's a comparison tool."],
    bajada:
      "Other sites show you products. Entreobra shows you which one is best for you, by price, stock, distance and who delivers.",
    ventajas: [
      "Same material, several suppliers",
      "One order, even if it comes from three hardware stores",
      "Every cost organized by site",
    ],
    producto: "Cement IP-30 · 50 bags",
    total: "Total",
    estadoFinal: "Sorted by total price",
    comparando: (n: string) => `Comparing ${n} hardware stores…`,
    mejorPrecio: "Best price",
    stock: ["180 bags in stock", "90 bags in stock", "stock not confirmed"],
    ahorras: ["You save ", " by choosing the best price from ", " suppliers"],
    nota: "Illustrative example: fictional stores and prices.",
    numeros: ["one", "two", "three", "four", "five"],
  },
  dosLados: {
    etiqueta: "Two sides",
    titulo: "One single platform.",
    bajada: "Entreobra sits between your job site and your supplier. Which side are you on?",
    lados: [
      {
        etiqueta: "If you're on site",
        palabra: "Site",
        titulo: ["Site managers, engineers", "and contractors"],
        puntos: [
          "Compare suppliers without leaving the site",
          "Order everything together, even from different places",
          "Your costs stay organized by project",
        ],
        cta: "Free · Get started",
      },
      {
        etiqueta: "If you sell materials",
        palabra: "Supplier",
        titulo: ["Hardware stores, distributors", "and importers"],
        puntos: [
          "Sites that don't know you yet will find you",
          "Get clear orders, without quoting by chat",
          "No commission per sale: a fixed fee, disclosed before any charge",
        ],
        cta: "Join as a founder",
      },
    ],
  },
  formulario: {
    etiqueta: "Early access",
    titulo: ["Be one of the first", "to use it."],
    bajada: "We're building the platform in Cochabamba. Leave your details and we'll let you know as soon as we open.",
    nombre: "Name",
    nombrePlaceholder: "Your name",
    participas: "How will you take part?",
    opciones: { obra: "I'm on a job site", proveedor: "I sell materials" },
    whatsapp: "WhatsApp",
    enviar: "Let me know when it opens",
    enviando: "Sending…",
    nota: "Free and no commitment. We'll only write when the platform is ready.",
    consentimiento: ["I accept the ", "Privacy policy", " and agree that Entreobra may contact me on WhatsApp about early access."],
    exitoTitulo: "Done, you're on the list.",
    waTitulo: "Just send the message.",
    waTexto: "We opened WhatsApp with your details already filled in. Send it and you're on the list.",
    abrirWa: "Open WhatsApp",
    enviarPorWa: "Send via WhatsApp",
    errorGenerico: "We couldn't send it. Please try again.",
    errorConexion: "We couldn't connect. Try again or send us your sign-up via WhatsApp.",
    mensajeWa: (nombre: string, participa: string, whatsapp: string) =>
      [
        "Hi, I'd like early access to Entreobra.",
        `Name: ${nombre}`,
        `Taking part as: ${participa}`,
        `My WhatsApp: ${whatsapp}`,
        "I accept Entreobra's Privacy policy.",
      ].join("\n"),
  },
  footer: {
    ubicacion: "Cochabamba, Bolivia",
    contacto: "Contact",
    siguenos: "Follow us",
  },
  instalar: {
    boton: "Install app",
    titulo: "Entreobra on your phone",
    sub: "Like any app, one tap away",
    iosCompartir: ["Tap the ", "share", " icon in the Safari bar."],
    iosAgregar: ["Scroll and choose ", "Add to Home Screen", "."],
    iosListo: ["Tap ", "Add", " at the top right. Done."],
    texto: "You get an icon like any app, it opens full screen and runs faster — without going through an app store.",
    instalar: "Install Entreobra",
    cerrar: "Close",
  },
  volverArriba: "Back to top",
  saltarContenido: "Skip to content",
  demo: {
    etiqueta: "Preview · Full app",
    titulo: "This is Entreobra on the inside.",
    bajada: "A preview of the app, beyond the landing page. Six moments: for the buyer, the seller and the driver.",
    avisoEtiqueta: "Preview · In development",
    avisoTitulo: "This is not the final product.",
    avisoTexto:
      "These screens show where Entreobra is heading. The app is in development: the design, data, companies and prices are examples, and may change before launch.",
    ctaTitulo: "Interested in moving this forward?",
    ctaTexto: "Tell us what you think.",
    ctaBoton: "Let's talk about it",
    volver: "Back to the landing page",
    appPorDentro: "The app on the inside",
    notaTelefono: "* Test screens. Design and data are subject to change.",
    pasos: [
      {
        titulo: "Your home",
        descripcion: "When you open the app you see what matters: your orders in progress, the companies that sell to you and your sites.",
        focos: [
          { titulo: "What you save, in plain sight", texto: "Every purchase made by comparing adds up the difference. You know how much Entreobra pays off." },
          { titulo: "Your current order, first", texto: "What's on the way shows up at the top, with the estimated arrival time." },
          { titulo: "The companies that sell to you", texto: "Hardware stores and distributors in Cochabamba with their rating, distance and whether they have stock." },
          { titulo: "Everything by site", texto: "Each site with its own orders and costs. Nothing gets mixed up." },
        ],
      },
      {
        titulo: "Search and compare",
        descripcion: "One catalog for every material, with prices from several hardware stores side by side.",
        focos: [
          { titulo: "Search the way you ask on site", texto: "Type “cement”, “rebar 3/8” or the brand. No codes, no PDF catalogs." },
          { titulo: "Filter in one tap", texto: "Cement, rebar, aggregates, bricks: tap a category and see only that." },
          { titulo: "Best price first", texto: "Each product tells you how many stores have it and from what price. Tap it and compare side by side." },
        ],
      },
      {
        titulo: "Build your order",
        descripcion: "Everything in one cart, even if the products come from different suppliers.",
        focos: [
          { titulo: "Grouped by store", texto: "If the order comes from two suppliers, you see what each one brings. It's still one order." },
          { titulo: "Quantities in a tap", texto: "Add or remove bags, bars or bricks without searching for the product again." },
          { titulo: "Delivered to your site", texto: "Choose the site and the day. The address is already saved." },
          { titulo: "One total, one button", texto: "Confirm once and each store receives its part of the order." },
        ],
      },
      {
        titulo: "Track it live",
        descripcion: "From the yard to the site: you know which step your order is at, at all times, without asking.",
        focos: [
          { titulo: "Watch it arrive", texto: "The truck on the map, from the warehouse to your site, in real time." },
          { titulo: "Know when it arrives", texto: "Estimated time, who's bringing it and in which vehicle. No need to call." },
          { titulo: "Every step, timestamped", texto: "Confirmed, being prepared, on the way, delivered. Everything is on record." },
        ],
      },
      {
        titulo: "If you run a hardware store",
        descripcion: "Publish your catalog and manage incoming orders from your own dashboard.",
        focos: [
          { titulo: "Your business at a glance", texto: "Orders, pending ones and sales, always up to date." },
          { titulo: "How the week is going", texto: "See which days you sell more so you have stock when it's needed." },
          { titulo: "Orders that come to you", texto: "Nearby sites order directly, ready to prepare. No chasing customers on WhatsApp." },
        ],
      },
      {
        titulo: "If you do deliveries",
        descripcion: "Get available deliveries near you and accept them with one tap.",
        focos: [
          { titulo: "Work when you want", texto: "Set yourself as available and deliveries near you start coming in." },
          { titulo: "From where to where", texto: "Origin, destination, distance and what you'll carry, before accepting." },
          { titulo: "Accept with one tap", texto: "The delivery is yours and the store already knows who's picking up the order." },
        ],
      },
    ],
  },
  app: {
    pestanasComprador: ["Home", "Search", "Order", "Sites"],
    pestanasFerreteria: ["Dashboard", "Orders", "Catalog", "Account"],
    pestanasChofer: ["Deliveries", "Route", "Earnings", "Profile"],
    inicio: {
      etiqueta: "Good morning",
      titulo: "Your sites",
      ahorro: "Saved this month",
      pedido: "Order #4821",
      enCamino: "On the way",
      llega: "Arrives in 25 min at Torre del Bosque",
      empresas: "Companies that sell to you",
      verTodas: "See all",
      conStock: "In stock",
      sinConfirmar: "Unconfirmed",
      obras: [
        { nombre: "Torre del Bosque", detalle: "3 orders · Bs 1,150" },
        { nombre: "Casa Sacaba #12", detalle: "1 order · Bs 480" },
      ],
    },
    catalogo: {
      etiqueta: "Torre del Bosque",
      titulo: "Catalog",
      buscar: "Search materials…",
      filtros: ["All", "Cement", "Rebar", "Aggregates"],
      productos: ["Cement IP-30", "Rebar 3/8", "Brick 6H", "Paint 20L", "Fine sand", 'PVC pipe 4"'],
      proveedores: (n: number) => `${n} suppliers`,
      desde: "from",
    },
    carrito: {
      etiqueta: "3 products · 2 suppliers",
      titulo: "Your order",
      productos: ["Cement IP-30", "Rebar 3/8", "Brick 6H"],
      entrega: "Delivery to site",
      entregaDetalle: "Torre del Bosque · tomorrow",
      total: "Total",
      confirmar: "Confirm order",
    },
    seguimiento: {
      etiqueta: "On the way",
      titulo: "Order #4821",
      llegaEn: "Arrives in",
      vehiculo: "Ferretería A · Toyota Dyna",
      estados: ["Confirmed", "Being prepared", "On the way", "Delivered"],
    },
    panel: {
      titulo: "My store",
      stats: ["Orders", "Pending", "Sold"],
      semana: "This week",
      entrantes: "Incoming orders",
      pedidos: [
        { obra: "Torre del Bosque building", detalle: "Cement IP-30 ×5" },
        { obra: "Casa Sacaba #12", detalle: "Rebar 3/8 ×10" },
        { obra: "Quillacollo warehouse", detalle: "Brick 6H ×200" },
      ],
      nuevo: "New",
      preparando: "Preparing",
    },
    fletes: {
      etiqueta: "Near you",
      titulo: "Deliveries",
      disponible: "Available",
      cargas: ["Cement ×5 · Rebar ×10", "Brick 6H ×200"],
      aceptar: "Accept",
    },
  },
};

export const TEXTOS = { es, en };
